
export const data=[
    {
      "id": 1,
      "img": "https://m.media-amazon.com/images/I/6125yAfsJKL._AC_UX575_.jpg",
      "title": "Nike Air Monarch IV",
      "reviews": "(123 reviews)",
      "prevPrice": 10500,
      "newPrice": 15000,
      "company": "Nike",
      "color": "white",
      "category": "sneakers",
      "priceId":"price_1NvDG7SBFVAeA67axSYGEZrH"
    },
    {
      "id": 2,
      "img": "https://m.media-amazon.com/images/I/519MRhRKGFL._AC_UX575_.jpg",
      "title": "Nike Air Vapormax Plus",
      "reviews": "(123 reviews)",
      "prevPrice": 12300,
      "newPrice": 10500,
      "company": "Nike",
      "color": "red",
      "category": "sneakers",
      "priceId":"price_1NvDL4SBFVAeA67aRu4cVjYr"
    },
    {
      "id": 3,
      "img": "https://m.media-amazon.com/images/I/51+P9uAvb1L._AC_UY695_.jpg",
      "title": "Nike Waffle One Sneaker",
      "reviews": "(123 reviews)",
      "prevPrice": 10500,
      "newPrice": 15000,
      "company": "Nike",
      "color": "green",
      "category": "sneakers",
      "priceId":"price_1NvDMLSBFVAeA67aCNCdS0jE"
    },
    {
      "id": 4,
      "img": "https://m.media-amazon.com/images/I/71oEKkghg-L._AC_UX575_.jpg",
      "title": "Nike Running Shoe",
      "reviews": "(123 reviews)",
      "prevPrice": 10500,
      "newPrice": 10000,
      "company": "Adidas",
      "color": "black",
      "category": "sneakers",
      "priceId":"price_1NvDODSBFVAeA67aQL5bRHfb"
    },
    {
      "id": 5,
      "img": "https://m.media-amazon.com/images/I/41M54ztS6IL._AC_SY625._SX._UX._SY._UY_.jpg",
      "title": "Flat Slip On Pumps",
      "reviews": "(123 reviews)",
      "prevPrice": 10500,
      "newPrice": 10400,
      "company": "Vans",
      "color": "green",
      "category": "flats",
      "priceId":"price_1NvDQ1SBFVAeA67anLcPEjZD"
    },
    {
      "id": 6,
      "img": "https://m.media-amazon.com/images/I/71zKuNICJAL._AC_UX625_.jpg",
      "title": "Knit Ballet Flat",
      "reviews": "(123 reviews)",
      "prevPrice": 3750,
      "newPrice": 3050,
      "company": "Adidas",
      "color": "black",
      "category": "flats",
      "priceId":"price_1NvDRISBFVAeA67aZFwj5gPC"
    },
    {
      "id": 7,
      "img": "https://m.media-amazon.com/images/I/61V9APfz97L._AC_UY695_.jpg",
      "title": "Loafer Flats",
      "reviews": "(123 reviews)",
      "prevPrice": 3750,
      "newPrice": 3750,
      "company": "Vans",
      "color": "white",
      "category": "flats",
      "priceId":"price_1NvDSDSBFVAeA67avtChHHlg"
    },
    {
      "id": 8,
      "img": "https://m.media-amazon.com/images/I/71VaQ+V6XnL._AC_UY695_.jpg",
      "title": "Nike Zoom Freak",
      "reviews": "(123 reviews)",
      "prevPrice": 10500,
      "newPrice": 15000,
      "company": "Nike",
      "color": "green",
      "category": "sneakers",
      "priceId":"price_1NvDTCSBFVAeA67aOSQ7oBRU"
    },
    {
      "id": 9,
      "img": "https://m.media-amazon.com/images/I/61-cBsLhJHL._AC_UY695_.jpg",
      "title": "Nike Men's Sneaker",
      "reviews": "(123 reviews)",
      "prevPrice": 10500,
      "newPrice": 11000,
      "company": "Adidas",
      "color": "blue",
      "category": "sneakers",
      "priceId":"price_1NvDUASBFVAeA67aUsWMNmyv"
    },
    {
      "id": 10,
      "img": "https://m.media-amazon.com/images/I/81xXDjojYKS._AC_UX575_.jpg",
      "title": "PUMA BLACK-OCE",
      "reviews": "(123 reviews)",
      "prevPrice": 11250,
      "newPrice": 11250,
      "company": "Puma",
      "color": "green",
      "category": "sneakers",
      "priceId":"price_1NvDUySBFVAeA67aDoKYpABz"
    },
    {
      "id": 11,
      "img": "https://m.media-amazon.com/images/I/71E75yRwCDL._AC_UY575_.jpg",
      "title": "Pacer Future Sneaker",
      "reviews": "(123 reviews)",
      "prevPrice": 10250,
      "newPrice": 11250,
      "company": "Puma",
      "color": "red",
      "category": "sneakers",
      "priceId":"price_1NvDW9SBFVAeA67ah9dhFsbK"
    },
    {
      "id": 12,
      "img": "https://m.media-amazon.com/images/I/71jeoX0rMBL._AC_UX575_.jpg",
      "title": "Unisex-Adult Super",
      "reviews": "(123 reviews)",
      "prevPrice": 11250,
      "newPrice": 11250,
      "company": "Puma",
      "color": "black",
      "category": "sneakers",
      "priceId":"price_1NvDX1SBFVAeA67a0jz70l0n"
    },
    {
      "id": 13,
      "img": "https://m.media-amazon.com/images/I/61TM6Q9dvxL._AC_UX575_.jpg",
      "title": "Roma Basic Sneaker",
      "reviews": "(123 reviews)",
      "prevPrice": 11250,
      "newPrice": 11250,
      "company": "Puma",
      "color": "white",
      "category": "sneakers",
      "priceId":"price_1NvDY6SBFVAeA67aelQndHki"
    },
    {
      "id": 14,
      "img": "https://m.media-amazon.com/images/I/7128-af7joL._AC_UY575_.jpg",
      "title": "Pacer Future Doubleknit",
      "reviews": "(123 reviews)",
      "prevPrice": 11250,
      "newPrice": 11050,
      "company": "Puma",
      "color": "black",
      "category": "sneakers",
      "priceId":"price_1NvDa3SBFVAeA67atqboZGox"
    },
    {
      "id": 15,
      "img": "https://m.media-amazon.com/images/I/81xXDjojYKS._AC_UX575_.jpg",
      "title": "Fusion Evo Golf Shoe",
      "reviews": "(123 reviews)",
      "prevPrice": 7500,
      "newPrice": 7500,
      "company": "Puma",
      "color": "green",
      "category": "sneakers",
      "priceId":"price_1NvDbcSBFVAeA67aAsy00vjE"
    },
    {
      "id": 16,
      "img": "https://m.media-amazon.com/images/I/719gdz8lsTS._AC_UX575_.jpg",
      "title": "Rainbow Chex Skate",
      "reviews": "(123 reviews)",
      "prevPrice": 7500,
      "newPrice": 7500,
      "company": "Vans",
      "color": "red",
      "category": "flats",
      "priceId":"price_1NvDcgSBFVAeA67aVIiXgwww"
    },
    {
      "id": 17,
      "img": "https://m.media-amazon.com/images/I/71gpFHJlnoL._AC_UX575_.jpg",
      "title": "Low-Top Trainers",
      "reviews": "(123 reviews)",
      "prevPrice": 7500,
      "newPrice": 7500,
      "company": "Vans",
      "color": "white",
      "category": "sandals",
      "priceId":"price_1NvDdWSBFVAeA67aVEPZLFds"
    },
    {
      "id": 18,
      "img": "https://m.media-amazon.com/images/I/71pf7VFs9CL._AC_UX575_.jpg",
      "title": "Vans Unisex Low-Top",
      "reviews": "(123 reviews)",
      "prevPrice": 7500,
      "newPrice": 7200,
      "company": "Vans",
      "color": "blue",
      "category": "sandals",
      "priceId":"price_1NvDeUSBFVAeA67as0tJB2ja"
    },
    {
      "id": 19,
      "img": "https://m.media-amazon.com/images/I/61N4GyWcHPL._AC_UY575_.jpg",
      "title": "Classic Bandana Sneakers",
      "reviews": "(123 reviews)",
      "prevPrice": 3750,
      "newPrice": 3050,
      "company": "Nike",
      "color": "black",
      "category": "sandals",
      "priceId":"price_1NvDfTSBFVAeA67a1doEBE3h"
    },
    {
      "id": 20,
      "img": "https://m.media-amazon.com/images/I/61bncQ44yML._AC_UX695_.jpg",
      "title": "Chunky High Heel",
      "reviews": "(123 reviews)",
      "prevPrice": 3750,
      "newPrice": 3750,
      "company": "Vans",
      "color": "black",
      "category": "heels",
      "priceId":"price_1NvDgWSBFVAeA67aIyWtLngK"
    },
    {
      "id": 21,
      "img": "https://m.media-amazon.com/images/I/71czu7WgGuL._AC_UY695_.jpg",
      "title": "Slip On Stiletto High Heel",
      "reviews": "(123 reviews)",
      "prevPrice": 10500,
      "newPrice": 9000,
      "company": "Puma",
      "color": "black",
      "category": "heels",
      "priceId":"price_1NvDhbSBFVAeA67aokP641Dc"
    },
    {
      "id": 22,
      "img": "https://m.media-amazon.com/images/I/61men05KRxL._AC_UY625_.jpg",
      "title": "DREAM PAIRS Court Shoes",
      "reviews": "(123 reviews)",
      "prevPrice": 10250,
      "newPrice": 10250,
      "company": "Nike",
      "color": "red",
      "category": "heels",
      "priceId":"price_1NvDj3SBFVAeA67ayVpVmg1H"
    },
    {
      "id": 23,
      "img": "https://m.media-amazon.com/images/I/519MRhRKGFL._AC_UX575_.jpg",
      "title": "Nike Air Vapormax Plus",
      "reviews": "(123 reviews)",
      "prevPrice": 11000,
      "newPrice": 8500,
      "company": "Nike",
      "color": "red",
      "category": "sneakers",
      "priceId":"price_1NvDkTSBFVAeA67aRGyaLaXQ"
    },
    {
      "id": 24,
      "img": "https://m.media-amazon.com/images/I/51PGWTXgf-L._AC_UY625_.jpg",
      "title": "Low Mid Block Heels",
      "reviews": "(123 reviews)",
      "prevPrice": 10000,
      "newPrice": 12000,
      "company": "Nike",
      "color": "black",
      "category": "heels",
      "priceId":"price_1NvDlbSBFVAeA67aEuyyz9ae"
    },
    {
      "id": 25,
      "img": "https://m.media-amazon.com/images/I/616sA5XUKtL._AC_UY675_.jpg",
      "title": "Chunky High Heel",
      "reviews": "(123 reviews)",
      "prevPrice": 3050,
      "newPrice": 2900,
      "company": "Adidas",
      "color": "black",
      "category": "heels",
      "priceId":"price_1NvDmkSBFVAeA67ag7b4HjlT"
    },
    {
      "id": 26,
      "img": "https://m.media-amazon.com/images/I/71h5+MbEK7L._AC_UY625_.jpg",
      "title": "Amore Fashion Stilettos",
      "reviews": "(123 reviews)",
      "prevPrice": 9250,
      "newPrice": 8999,
      "company": "Adidas",
      "color": "white",
      "category": "heels",
      "priceId":"price_1NvDoLSBFVAeA67aBNxF3115"
    },
    {
      "id": 27,
      "img": "https://m.media-amazon.com/images/I/61uw5RDxKQL._AC_UY625_.jpg",
      "title": "Bridal Sandals Glitter",
      "reviews": "(123 reviews)",
      "prevPrice": 3750,
      "newPrice": 2999,
      "company": "Adidas",
      "color": "black",
      "category": "heels",
      "priceId":"price_1NvDpdSBFVAeA67anGwODdhQ"
    },
    {
      "id": 28,
      "img": "https://m.media-amazon.com/images/I/71yhoZP0l6L._AC_UY695_.jpg",
      "title": "Wedding Prom Bridal",
      "reviews": "(123 reviews)",
      "prevPrice": 3750,
      "newPrice": 3750,
      "company": "Adidas",
      "color": "black",
      "category": "flats",
      "priceId":"price_1NvDqlSBFVAeA67ag1w8Ta6N"
    }
  ]
  

